import { Router, type IRouter } from "express";
import healthRouter from "./health";
import snowRouter from "./snow";
import placesRouter from "./places";
import placesGoogleRouter from "./places-google";
import weatherTilesRouter from "./weather-tiles";
import weatherRouter from "./weather";
import townWeatherRouter from "./town-weather";
import townEnsembleRouter from "./town-ensemble";
import busRouter from "./bus";
import webcamsRouter from "./webcams";
import roadsRouter from "./roads";
import vicEmergencyRouter from "./vic-emergency";
import liftsRouter from "./lifts";
import radarRouter from "./radar";
import regionsRouter from "./regions";
import sentryTestRouter from "./sentry-test";
import alertsSubscriptionsRouter from "./alerts-subscriptions";
import alertsPushRouter from "./alerts-push";
import alertsInternalRouter from "./alerts-internal";
import smokeInternalRouter from "./smoke-internal";
import elevationForecastRouter from "./elevation-forecast";
import authRouter from "./auth";
import accountRouter from "./account";
import authEmailRouter from "./auth-email";
import promoRouter from "./promo";
import engagementRouter from "./engagement";
import resendWebhookRouter from "./resend-webhook";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sentryTestRouter);
router.use(snowRouter);
router.use(placesRouter);
router.use(placesGoogleRouter);
router.use(weatherTilesRouter);
router.use(weatherRouter);
router.use(townWeatherRouter);
router.use(townEnsembleRouter);
router.use(busRouter);
router.use(webcamsRouter);
router.use(roadsRouter);
router.use(vicEmergencyRouter);
router.use(liftsRouter);
router.use(radarRouter);
router.use(regionsRouter);
router.use(alertsSubscriptionsRouter);
router.use(alertsPushRouter);
router.use(alertsInternalRouter);
router.use(smokeInternalRouter);
router.use(elevationForecastRouter);
router.use(authRouter);
router.use(accountRouter);
router.use(authEmailRouter);
router.use(promoRouter);
router.use(engagementRouter);
router.use(resendWebhookRouter);
router.use("/admin", adminRouter);

export default router;
