// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/feelzlike-branding/LogoV1.tsx": () => import("../components/mockups/feelzlike-branding/LogoV1.tsx"),
  "./components/mockups/feelzlike-branding/LogoV2.tsx": () => import("../components/mockups/feelzlike-branding/LogoV2.tsx"),
  "./components/mockups/feelzlike-branding/LogoV3.tsx": () => import("../components/mockups/feelzlike-branding/LogoV3.tsx"),
  "./components/mockups/landing-mobile/LiveDataHero.tsx": () => import("../components/mockups/landing-mobile/LiveDataHero.tsx"),
  "./components/mockups/landing-mobile/PhotoLed.tsx": () => import("../components/mockups/landing-mobile/PhotoLed.tsx")
};
