import {
  Home,
  Mountain,
  Video,
  Car,
  Cable,
  Bus,
  BedDouble,
  UtensilsCrossed,
  Compass,
  AlertTriangle,
} from "lucide-react";
import type { RegionConfig } from "@workspace/feelzlike-shell";
import wordmark from "@assets/feelzlike_trimmed/feelzlike_WordMarque_colour_160426_1777334678269_trim.png";

export const yamanouchiRegion: RegionConfig = {
  id: "yamanouchi",
  name: "Yamanouchi",
  subtitle: "Nagano · Japan",
  shortTag: "JP",
  brand: { wordmarkUrl: wordmark },
  seasons: true,
  language: { locales: ["en", "ja"] },
  nav: [
    { path: "/",          icon: Home,           label: "Today",     labelJa: "今日" },
    { path: "/mountains", icon: Mountain,       label: "Mountains", labelJa: "スキー場" },
    { path: "/cams",      icon: Video,          label: "Cams",      labelJa: "ライブ" },
    { path: "/roads",     icon: Car,            label: "Roads",     labelJa: "道路" },
    { path: "/lifts",     icon: Cable,          label: "Lifts",     labelJa: "リフト", season: "winter" },
    { path: "/transport", icon: Bus,            label: "Transport", labelJa: "交通", group: "secondary" },
    { path: "/stay",      icon: BedDouble,      label: "Stay",      labelJa: "宿泊", group: "secondary" },
    { path: "/eat",       icon: UtensilsCrossed,label: "Eat",       labelJa: "食事", group: "secondary" },
    { path: "/explore",   icon: Compass,        label: "Explore",   labelJa: "観光", group: "secondary" },
    { path: "/alerts",    icon: AlertTriangle,  label: "Alerts",    labelJa: "警報", group: "secondary" },
  ],
  resorts: [
    { path: "/mountain/shiga-kogen",   label: "Shiga Kogen",      labelJa: "志賀高原" },
    { path: "/mountain/yakebitaiyama", label: "Yakebitaiyama",    labelJa: "焼額山" },
    { path: "/mountain/kita-shiga",    label: "Kita-Shiga Kogen", labelJa: "北志賀高原" },
    { path: "/mountain/ryuoo",         label: "Ryuoo",            labelJa: "竜王" },
  ],
  mountains: [
    { id: "shiga-kogen",   name: "Shiga Kogen",      nameJa: "志賀高原",    elevationM: 2307, blurb: "Japan's largest interconnected ski area · 18 resorts", blurbJa: "日本最大の連結スキー場 · 18エリア" },
    { id: "yakebitaiyama", name: "Yakebitaiyama",    nameJa: "焼額山",      elevationM: 2009, blurb: "World Cup slopes inside Shiga Kogen",                  blurbJa: "志賀高原内のワールドカップ斜面" },
    { id: "kita-shiga",    name: "Kita-Shiga Kogen", nameJa: "北志賀高原",  elevationM: 1930, blurb: "North-facing powder · close to Yomase",                blurbJa: "北向き斜面のパウダー · 夜間瀬に近い" },
    { id: "ryuoo",         name: "Ryuoo",            nameJa: "竜王",         elevationM: 1930, blurb: "Sea-of-clouds gondola summit",                          blurbJa: "雲海ゴンドラの山頂" },
  ],
  baseTowns: [
    {
      id: "yudanaka",
      name: "Yudanaka",
      nameJa: "湯田中",
      lat: 36.7460,
      lng: 138.4280,
      radiusM: 2500,
      blurb: "Onsen station town · gateway to Shiga Kogen",
      blurbJa: "温泉駅前 · 志賀高原への玄関口",
    },
    {
      id: "shibu-onsen",
      name: "Shibu Onsen",
      nameJa: "渋温泉",
      lat: 36.7517,
      lng: 138.4286,
      radiusM: 2000,
      blurb: "Historic ryokan village · cobbled lanes & nine bathhouses",
      blurbJa: "歴史ある旅館街 · 石畳と九湯めぐり",
    },
    {
      id: "yomase",
      name: "Yomase",
      nameJa: "夜間瀬",
      lat: 36.7710,
      lng: 138.4080,
      radiusM: 3500,
      blurb: "Quieter base on the river · close to Kita-Shiga lifts",
      blurbJa: "夜間瀬川沿いの静かな拠点 · 北志賀のリフトに近い",
    },
  ],
  footer: "v0.3 · feelzlike",
  roadsSource: {
    label: "Japan Road Traffic Information Center (JARTIC)",
    labelJa: "日本道路交通情報センター (JARTIC)",
    url: "https://www.jartic.or.jp/",
    dataAvailable: false,
  },
};
