/**
 * Dependency-free JSON Schema for storage/API boundaries. Runtime consumers can
 * import this without pulling frontend TypeScript or asset modules.
 */
export const japanCatalogueSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://feelzlike.com/schemas/japan-ski-catalogue-v1.json",
  title: "Canonical Japan ski-area catalogue",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "countryCode",
    "generatedAt",
    "sources",
    "policy",
    "frontendRegionSources",
    "travelRegions",
    "intakeRecords",
    "publishedPages",
    "publicationCandidates",
    "publishedCatalogueRecords",
  ],
  properties: {
    schemaVersion: { const: 1 },
    countryCode: { const: "JP" },
    generatedAt: { type: "string", format: "date-time" },
    sources: { type: "array", items: { type: "object" } },
    policy: {
      type: "object",
      required: [
        "launchPolicyId",
        "launchPolicyDescription",
        "allowedLifecycles",
        "publishableOperatingStatuses",
        "marketingApproved",
        "marketingGateReason",
        "cleanGate",
      ],
      properties: {
        launchPolicyId: { const: "verified_evidence_complete_only" },
        launchPolicyDescription: { type: "string", minLength: 1 },
        allowedLifecycles: {
          const: ["draft", "verified", "published"],
        },
        publishableOperatingStatuses: { const: ["operating"] },
        marketingApproved: { type: "boolean" },
        marketingGateReason: { type: "string", minLength: 1 },
        cleanGate: {
          type: "object",
          required: [
            "verifiedEvidenceCompleteRecords",
            "lifecyclePublishedRecords",
            "routeReadyNewCandidates",
            "manifestIntegratedNewRecords",
            "reviewQueueExcludedPendingEvidence",
            "unclearOrNotVerifiableRecords",
            "verifiedEssentialGapRecords",
          ],
          properties: {
            verifiedEvidenceCompleteRecords: { type: "integer", minimum: 0 },
            lifecyclePublishedRecords: { type: "integer", minimum: 0 },
            routeReadyNewCandidates: { type: "integer", minimum: 0 },
            manifestIntegratedNewRecords: { type: "integer", minimum: 0 },
            reviewQueueExcludedPendingEvidence: { type: "integer", minimum: 0 },
            unclearOrNotVerifiableRecords: { type: "integer", minimum: 0 },
            verifiedEssentialGapRecords: { type: "integer", minimum: 0 },
          },
        },
      },
    },
    frontendRegionSources: { type: "array", items: { type: "object" } },
    travelRegions: { type: "array", minItems: 1, items: { type: "object" } },
    intakeRecords: {
      type: "array",
      items: {
        type: "object",
        required: [
          "recordId",
          "lifecycle",
          "operatingStatus",
          "source",
          "raw",
          "evidence",
          "directoryRelationship",
          "readiness",
          "resolved",
          "publicationReadiness",
        ],
        properties: {
          lifecycle: { enum: ["draft", "verified", "published"] },
          operatingStatus: {
            enum: [
              "operating",
              "temporarily_closed",
              "indoor",
              "dry_slope",
              "closed",
              "unknown",
            ],
          },
          reviewedOperatingStatus: {
            enum: ["operating", "temporarily_closed", "closed", "merged_into"],
          },
          travelRegionId: { type: "string", minLength: 1 },
          baseTownId: { type: "string", minLength: 1 },
          publicId: { type: "string", minLength: 1 },
          aliases: { type: "array", items: { type: "string", minLength: 1 } },
          routeMode: { enum: ["existing_page", "new_page"] },
          existingPageId: { type: "string", minLength: 1 },
          review: {
            type: "object",
            required: [
              "reviewBatch",
              "reviewedAt",
              "reviewStatus",
              "evidenceAsOf",
              "travelClusterLabelSuggestion",
              "baseTownLabelSuggestion",
              "clusterConfidence",
            ],
          },
          publicationReadiness: {
            type: "object",
            required: ["publishable", "missingReasons"],
            properties: {
              publishable: { type: "boolean" },
              routeAlreadyPublished: { type: "boolean" },
              missingReasons: { type: "array", items: { type: "string" } },
            },
          },
          resolved: { type: "object" },
        },
      },
    },
    publishedPages: {
      type: "array",
      items: {
        type: "object",
        required: [
          "pageRecordId",
          "publicId",
          "aliases",
          "route",
          "lifecycle",
          "operatingStatus",
          "travelRegionId",
          "baseTownId",
          "coordinates",
          "elevationM",
          "verificationDate",
          "evidence",
          "intakeRelationship",
        ],
        properties: {
          lifecycle: { const: "published" },
          operatingStatus: { const: "operating" },
        },
      },
    },
    publicationCandidates: {
      type: "array",
      items: {
        type: "object",
        required: [
          "recordId",
          "publicId",
          "aliases",
          "travelRegionId",
          "baseTownId",
          "route",
          "name",
          "nameJa",
          "coordinates",
          "elevation",
          "officialUrl",
          "evidence",
        ],
      },
    },
    publishedCatalogueRecords: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "recordId",
          "publicId",
          "aliases",
          "name",
          "nameJa",
          "coordinates",
          "forecastElevationM",
          "baseElevationM",
          "topElevationM",
          "officialUrl",
          "travelRegionId",
          "baseTownId",
          "route",
          "prefecture",
          "country",
          "countryCode",
          "honesty",
        ],
        properties: {
          recordId: { type: "string" },
          publicId: { type: "string" },
          aliases: { type: "array", items: { type: "string" } },
          name: { type: "string" },
          nameJa: { type: "string" },
          coordinates: {
            type: "object",
            required: ["lat", "lng"],
            properties: { lat: { type: "number" }, lng: { type: "number" } },
          },
          forecastElevationM: { type: "number" },
          baseElevationM: { type: "number" },
          topElevationM: { type: "number" },
          officialUrl: { type: "string" },
          travelRegionId: { type: "string" },
          baseTownId: { type: "string" },
          route: { type: "string" },
          prefecture: { type: "string" },
          country: { const: "Japan" },
          countryCode: { const: "JP" },
          honesty: {
            type: "object",
            additionalProperties: false,
            required: [
              "operatingStatusVerified",
              "evidenceComplete",
              "manifestApproved",
              "runtimeIntegrated",
            ],
            properties: {
              operatingStatusVerified: { const: true },
              evidenceComplete: { const: true },
              manifestApproved: { const: true },
              runtimeIntegrated: { const: true },
            },
          },
        },
      },
    },
  },
};

export const japanDiscoveryReconciliationSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://feelzlike.com/schemas/japan-discovery-reconciliation-v1.json",
  title: "Japan ski-area discovery reconciliation",
  type: "object",
  additionalProperties: false,
  required: ["schemaVersion", "generatedAt", "policy", "sources", "sourceEntries", "areas"],
  properties: {
    schemaVersion: { const: 1 },
    generatedAt: { type: "string", format: "date-time" },
    policy: {
      type: "object",
      required: ["discoveryPresenceIsOperatingEvidence", "completenessClaim"],
      properties: {
        discoveryPresenceIsOperatingEvidence: { const: false },
        completenessClaim: { type: "string", minLength: 1 },
      },
    },
    sources: { type: "array", minItems: 4, items: { type: "object" } },
    sourceEntries: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        required: [
          "sourceEntryId",
          "sourceId",
          "sourceName",
          "sourceUrl",
          "retrievalDate",
          "originalName",
          "normalizedIdentity",
          "prefecture",
        ],
      },
    },
    areas: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        required: [
          "identityId",
          "canonicalName",
          "normalizedIdentity",
          "prefecture",
          "sourceMembership",
          "sourceEntryIds",
          "operatingEvidence",
          "publicCoverage",
          "disposition",
        ],
        properties: {
          disposition: {
            enum: [
              "published_directly",
              "covered_by_alias",
              "covered_by_multiple_pages",
              "merged_or_renamed",
              "closed",
              "out_of_scope",
              "genuinely_missing",
              "unresolved",
            ],
          },
        },
      },
    },
  },
};